# Generated by Django 6.0 on 2025-12-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="pokemon_types",
            field=models.ManyToManyField(blank=True, to="pokedex.pokemontype"),
        ),
    ]
