# Generated by Django 6.0 on 2025-12-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("temp_f", models.IntegerField()),
                ("iced", models.BooleanField()),
                ("size_in_ounces", models.FloatField()),
                ("caffeine_in_mg", models.IntegerField()),
            ],
        ),
    ]
