# Generated by Django 6.0 on 2025-12-09 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("morning_bevs_api", "0002_brand_category_beverage_brand_beverage_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beverage",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beverages",
                to="morning_bevs_api.brand",
            ),
        ),
    ]
