# Generated by Django 6.0 on 2025-12-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("age", models.IntegerField()),
                ("address", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="LottoNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winning_numbers", models.IntegerField()),
                ("date", models.DateField()),
                ("location", models.CharField()),
                ("dollar_amount", models.FloatField()),
                ("rounds_not_won", models.IntegerField()),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lottery.winner",
                    ),
                ),
            ],
        ),
    ]
