# Generated by Django 6.0 on 2025-12-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lottonumber",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
