# Generated by Django 6.0 on 2025-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lottery", "0002_alter_lottonumber_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="winner",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
