# Generated by Django 5.2.8 on 2025-12-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(default="hello", unique=True),
            preserve_default=False,
        ),
    ]
