# Generated by Django 5.2.8 on 2025-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_book_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("background", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
    ]
